### ISSUE TITLE
点击国际会议管理项目下的国际会议申报的下载按钮,会议申报的会议规模未填写的下载报错(开发和121模式)

### ISSUE THREAD

**Issue by liyangfl** [jshand/cmu#10]
![图片1](https://user-images.githubusercontent.com/44664410/59753123-0fe6d500-92b6-11e9-8843-dd66bec97f2d.png)
![图片2](https://user-images.githubusercontent.com/44664410/59753124-107f6b80-92b6-11e9-8756-9f2054a558a7.png)

**Comment by jshand** [comment]
已提交代码，请回归测试
