### ISSUE TITLE
三种模式下的学生交流项目管理下的交流项目设定的创建项目的项目专业限制多选后报错,后台提示超出最大值

### ISSUE THREAD

**Issue by liyangfl** [jshand/cmu#3]
![图片1](https://user-images.githubusercontent.com/44664410/58600262-792a8800-82b6-11e9-9f27-05e510557170.png)
![图片1](https://user-images.githubusercontent.com/44664410/58861630-61516a80-86e1-11e9-8ff2-dce696cde492.png)

**Comment by jshand** [comment]
已修复
