### ISSUE TITLE
三种模式下的外宾来访接待的接待申请的导出pdf,导出文件在备注没有领导信息,来访接待总结没有填写领导信息的位置和提示

### ISSUE THREAD

**Issue by liyangfl** [jshand/cmu#6]
![图片1](https://user-images.githubusercontent.com/44664410/58674727-a98c2800-8383-11e9-8c37-14308e12a0f1.png)

**Comment by jshand** [comment]
现在选择邀请校领导，已经能在备注中提示 输入校领导信息了，请测试

**Comment by liyangfl** [comment]
来访接待总结选择邀请校领导,没有填写领导信息的位置和提示(更改是否选中校领导备注中显示的还是原来信息)
外宾来访接待的接待申请的导出pdf,导出文件在备注校领导名字显示
